<a href="https://colab.research.google.com/github/syedmahmoodiagents/computervision/blob/main/ComputerVision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import load_digits

In [ ]:
dt = load_digits(n_class=3)

In [ ]:
images = dt.images

In [ ]:
Y = dt.target

In [ ]:
images[-2]

array([[ 0.,  0., 15., 13.,  1.,  0.,  0.,  0.],
       [ 0.,  0., 14., 14.,  4.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  4., 12.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  6., 12.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 11., 10.,  0.,  0.,  0.],
       [ 0.,  0.,  1., 16.,  8.,  6.,  5.,  0.],
       [ 0.,  0., 13., 16., 16., 16., 14.,  0.],
       [ 0.,  0., 10., 13., 10.,  6.,  2.,  0.]])

In [ ]:
Y[-2]

np.int64(2)

In [ ]:
images[0].reshape(1, 64)

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
        15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
        12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
         0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
        10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [ ]:
images.shape

(537, 8, 8)

In [ ]:
X = images.reshape(-1,64)

In [ ]:
X.shape

(537, 64)

In [ ]:
X = torch.FloatTensor(X)
Y = torch.LongTensor(Y)

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

In [ ]:
model = nn.Sequential(
    nn.Linear(64, 32),
    nn.ReLU(),
    nn.Linear(32, 3),
)

In [ ]:
# model(X)

In [ ]:
# nn.NLLLoss()

In [ ]:
lossfn = nn.CrossEntropyLoss()

In [ ]:
opt = optim.Adam(model.parameters(), lr=0.01)

In [ ]:
for _ in range(30):
    opt.zero_grad()
    Yp = model(X)
    loss = lossfn(Yp, Y)
    loss.backward()
    opt.step()
    print(loss)

tensor(1.1451, grad_fn=<NllLossBackward0>)
tensor(1.3613, grad_fn=<NllLossBackward0>)
tensor(0.1810, grad_fn=<NllLossBackward0>)
tensor(0.3937, grad_fn=<NllLossBackward0>)
tensor(0.3058, grad_fn=<NllLossBackward0>)
tensor(0.1442, grad_fn=<NllLossBackward0>)
tensor(0.0997, grad_fn=<NllLossBackward0>)
tensor(0.1006, grad_fn=<NllLossBackward0>)
tensor(0.0839, grad_fn=<NllLossBackward0>)
tensor(0.0526, grad_fn=<NllLossBackward0>)
tensor(0.0369, grad_fn=<NllLossBackward0>)
tensor(0.0442, grad_fn=<NllLossBackward0>)
tensor(0.0596, grad_fn=<NllLossBackward0>)
tensor(0.0582, grad_fn=<NllLossBackward0>)
tensor(0.0422, grad_fn=<NllLossBackward0>)
tensor(0.0256, grad_fn=<NllLossBackward0>)
tensor(0.0152, grad_fn=<NllLossBackward0>)
tensor(0.0118, grad_fn=<NllLossBackward0>)
tensor(0.0128, grad_fn=<NllLossBackward0>)
tensor(0.0144, grad_fn=<NllLossBackward0>)
tensor(0.0142, grad_fn=<NllLossBackward0>)
tensor(0.0123, grad_fn=<NllLossBackward0>)
tensor(0.0103, grad_fn=<NllLossBackward0>)
tensor(0.00

In [ ]:
model(X)

In [ ]:
# pip install opencv-python

In [ ]:
import cv2

In [ ]:
ar = cv2.imread('one.png')

In [ ]:
ar.shape

(121, 137, 3)

In [ ]:
grar = cv2.cvtColor(ar, cv2.COLOR_BGR2GRAY)

In [ ]:
rszar = cv2.resize(grar, (8, 8))

In [ ]:
far = rszar.reshape(1, 64)

In [ ]:
far

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  59,
          0,   0,   0,   0,   0,   0,   0, 118,   0,   0,   0,   0,   0,
          0,   1, 118,   0,   0,   0,   0,   0,   0,   0, 118,   0,   0,
          0,   0,   0,   0,   0, 118,   0,   0,   0,   0,   0,   0, 118,
        118, 102,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]],
      dtype=uint8)

In [ ]:
fimg = torch.FloatTensor(far)

In [ ]:
model(fimg)

tensor([[-53.2309,  21.7276,  26.5435]], grad_fn=<AddmmBackward0>)

In [ ]:
sfx = torch.softmax(model(fimg), dim=1)

In [ ]:
torch.argmax(sfx, dim=1)

tensor([2])